/**
 * Client/server-safe metadata package for browser-first commit-bundle.
 * Builds JSON/markdown text files the commit path needs — does not run Sharp
 * or rewrite the full export orchestrator.
 */

import {
  accessionDraftToArchiveDraft,
  draftToArchiveEntry,
} from "./adapters";
import { buildArchiveBundleFiles } from "./generate-entry";
import {
  ARCHIVE_IMAGE_OUTPUTS,
  archiveImageOutputFilenames,
} from "./image-specs";
import {
  AccessionDraftSchema,
  ArchiveEntrySchema,
  defaultArchiveAssets,
  type AccessionDraft,
  type ArchiveEntry,
  type DerivativeAsset,
  type DraftStatus,
} from "./schema";

export interface BrowserDerivativeMeta {
  filename: string;
  width: number;
  height: number;
  byteSize: number;
  mimeType?: string;
}

export interface MetadataPackageFile {
  path: string;
  content: string;
}

export interface BrowserMetadataPackage {
  slug: string;
  draftId: string;
  entry: ArchiveEntry;
  draft: AccessionDraft;
  files: MetadataPackageFile[];
  warnings: string[];
}

function roleForFilename(filename: string): DerivativeAsset["role"] {
  if (filename === ARCHIVE_IMAGE_OUTPUTS.thumbJpg.filename) return "thumb";
  if (filename === ARCHIVE_IMAGE_OUTPUTS.socialJpg.filename) return "social";
  if (filename === ARCHIVE_IMAGE_OUTPUTS.artwork.filename) return "artwork";
  return "preview";
}

function formatForFilename(filename: string): string {
  if (filename.endsWith(".avif")) return "avif";
  if (filename.endsWith(".webp")) return "webp";
  if (filename.endsWith(".jpg") || filename.endsWith(".jpeg")) return "jpeg";
  if (filename.endsWith(".png")) return "png";
  return "bin";
}

export function buildDerivativeAssetsFromBrowserMeta(
  slug: string,
  metas: BrowserDerivativeMeta[],
  generatedAt = new Date().toISOString(),
): DerivativeAsset[] {
  const byName = new Map(metas.map((m) => [m.filename, m]));
  return archiveImageOutputFilenames().map((filename) => {
    const meta = byName.get(filename);
    return {
      role: roleForFilename(filename),
      path: `/archive/${slug}/${filename}`,
      format: formatForFilename(filename),
      width: meta?.width ?? 1,
      height: meta?.height ?? 1,
      byteSize: meta?.byteSize ?? 0,
      generatedAt,
    };
  });
}

/**
 * Build metadata.json / states.json / notes.md / draft sidecars for commit-bundle.
 */
export function buildBrowserMetadataPackage(input: {
  draft: AccessionDraft;
  derivativeMetas: BrowserDerivativeMeta[];
  existingEntry?: ArchiveEntry | null;
  status?: DraftStatus;
}): BrowserMetadataPackage {
  const parsedDraft = AccessionDraftSchema.parse(input.draft);
  const generatedAt = new Date().toISOString();
  const nextStatus: DraftStatus = input.status ?? "generated";

  const archiveDraft = accessionDraftToArchiveDraft(parsedDraft);
  archiveDraft.status = nextStatus === "prepared" ? "draft" : nextStatus;

  const generatedEntry = draftToArchiveEntry(archiveDraft);
  const existing = input.existingEntry ?? undefined;
  const derivatives = buildDerivativeAssetsFromBrowserMeta(
    parsedDraft.slug,
    input.derivativeMetas,
    generatedAt,
  );

  const entry: ArchiveEntry = ArchiveEntrySchema.parse({
    ...generatedEntry,
    createdAt: existing?.createdAt ?? generatedEntry.createdAt,
    status: existing?.status ?? "generated",
    publishedAt: existing?.publishedAt ?? generatedEntry.publishedAt,
    mintedAt: existing?.mintedAt ?? generatedEntry.mintedAt,
    hiddenAt: existing?.hiddenAt ?? generatedEntry.hiddenAt,
    withdrawnAt: existing?.withdrawnAt ?? generatedEntry.withdrawnAt,
    provenance: existing?.provenance ?? generatedEntry.provenance,
    exports: existing?.exports ?? generatedEntry.exports,
    accessionId: existing?.accessionId ?? generatedEntry.accessionId,
    source: existing?.source ?? parsedDraft.source ?? generatedEntry.source,
    processing: parsedDraft.processing?.preparedSource
      ? {
          ...parsedDraft.processing,
          preparedSource: "prepared/master-prepared.avif",
        }
      : existing?.processing ?? parsedDraft.processing,
    assets: defaultArchiveAssets(parsedDraft.slug),
    derivatives,
    metadata: {
      ...generatedEntry.metadata,
      accessionId:
        existing?.metadata.accessionId ??
        existing?.accessionId ??
        generatedEntry.metadata.accessionId,
    },
    updatedAt: generatedAt,
  });

  // First-time generate should leave status as generated on the archive entry.
  if (!existing) {
    entry.status = "generated";
    delete entry.publishedAt;
  }

  const incompleteNote = [
    "BROWSER_MVP_INCOMPLETE",
    "This accession was generated by the browser-first commit path.",
    "Included: metadata.json, states.json, notes.md, and the five public derivatives.",
    "Excluded from this MVP package: perception.html (standalone HTML) and manifest.json.",
    "Excluded workflows until a full regenerate: mint-package export and offline HTML distribution.",
    "Sync/publish validation only requires metadata.json + public derivatives.",
    "Public Next.js archive pages need a redeploy to pick up GitHub tip content.",
  ].join(" ");

  const warnings: string[] = [];
  if (!entry.metadata.title.trim()) {
    warnings.push("Title is empty; slug may be the only public label.");
  }
  if (entry.perception.states.length === 0) {
    warnings.push("No perceptual states defined.");
  }
  warnings.push(
    "Incomplete browser MVP package: perception.html and manifest.json were not written. Mint-package export is unavailable until a full local regenerate. Public View remains redeploy-bound.",
  );

  entry.processing = {
    ...entry.processing,
    prepareVersion:
      entry.processing?.prepareVersion ?? "browser-mvp-v1-no-html-manifest",
  };
  entry.metadata = {
    ...entry.metadata,
    perceptualNotes: entry.metadata.perceptualNotes
      ? `${entry.metadata.perceptualNotes}\n\n${incompleteNote}`
      : incompleteNote,
  };

  const bundle = buildArchiveBundleFiles(entry);
  const notesWithBanner = [
    "> BROWSER MVP INCOMPLETE PACKAGE",
    ">",
    "> Written: metadata.json, states.json, notes.md, five public derivatives.",
    "> Not written: perception.html, manifest.json.",
    "> Mint-package and offline HTML export are excluded until full regenerate.",
    "",
    bundle.notesMd.endsWith("\n") ? bundle.notesMd.slice(0, -1) : bundle.notesMd,
    "",
  ].join("\n");

  const updatedDraft = AccessionDraftSchema.parse({
    ...parsedDraft,
    status: nextStatus,
    generatedAt: nextStatus === "generated" ? generatedAt : parsedDraft.generatedAt,
    preparedAt:
      nextStatus === "prepared" ? generatedAt : parsedDraft.preparedAt,
    updatedAt: generatedAt,
    processing: {
      ...parsedDraft.processing,
      prepareVersion:
        parsedDraft.processing.prepareVersion ??
        "browser-mvp-v1-no-html-manifest",
    },
  });

  const statesSidecar = {
    version: updatedDraft.version,
    draftId: updatedDraft.draftId,
    slug: updatedDraft.slug,
    perception: {
      states: updatedDraft.artwork.states,
      background: updatedDraft.artwork.background,
      initialAngle: updatedDraft.artwork.initialAngle,
      snapToState: updatedDraft.artwork.snapToState,
      showMetadataOverlay: updatedDraft.artwork.showMetadataOverlay,
      overlayFields: updatedDraft.artwork.overlayFields,
    },
    updatedAt: updatedDraft.updatedAt,
    browserMvpIncomplete: {
      missing: ["perception.html", "manifest.json"],
      excluded: ["mint-package", "offline-html-distribution"],
    },
  };

  const files: MetadataPackageFile[] = [
    {
      path: `content/archive/${entry.slug}/metadata.json`,
      content: `${JSON.stringify(entry, null, 2)}\n`,
    },
    {
      path: `content/archive/${entry.slug}/states.json`,
      content: `${bundle.statesJson}\n`,
    },
    {
      path: `content/archive/${entry.slug}/notes.md`,
      content: notesWithBanner.endsWith("\n")
        ? notesWithBanner
        : `${notesWithBanner}\n`,
    },
    {
      path: `content/drafts/${updatedDraft.draftId}/draft.json`,
      content: `${JSON.stringify(updatedDraft, null, 2)}\n`,
    },
    {
      path: `content/drafts/${updatedDraft.draftId}/states.json`,
      content: `${JSON.stringify(statesSidecar, null, 2)}\n`,
    },
  ];

  return {
    slug: entry.slug,
    draftId: updatedDraft.draftId,
    entry,
    draft: updatedDraft,
    files,
    warnings,
  };
}
